"""
flasher-v2.0.0.py
Hybrid RobotiX — HybX Development System v2.0
Dale Weber <hybotix@hybridrobotix.io>

HybX flasher module. Flashes a compiled binary to the MCU via OpenOCD.
Replaces the manual OpenOCD dance and arduino-app-cli's unreliable
flash_sketch_ram.cfg → flash_sketch.cfg fallback sequence.

Always writes to flash (never RAM). Always uses the correct binary
(sketch.ino.elf-zsk.bin). No intermediate steps, no surprises.

Usage:
    from flasher import HybXFlasher
    flasher = HybXFlasher(board, binary_path)
    result = flasher.flash()
    if result.success:
        print(f"[timer] flash: {result.elapsed:.3f}s")
    else:
        print(f"ERROR: {result.error}")

License: MIT
"""

import os
import subprocess
import tempfile
import time
from dataclasses import dataclass
from typing import Optional


# ── Flash result ───────────────────────────────────────────────────────────────

@dataclass
class FlashResult:
    success:  bool          = False
    elapsed:  float         = 0.0
    error:    Optional[str] = None


# ── Flasher ────────────────────────────────────────────────────────────────────

class HybXFlasher:
    """
    Flashes a compiled binary to the MCU via OpenOCD over SWD.

    board       : board definition dict loaded from boards/uno-q.json
    binary_path : path to the .elf-zsk.bin file to flash.
                  If None, looks for sketch.ino.elf-zsk.bin in the
                  app's .cache/sketch/ directory.
    app_path    : app directory (used to locate binary if binary_path
                  is None)
    verbose     : if True, print OpenOCD output
    """

    def __init__(self,
                 board:       dict,
                 binary_path: Optional[str] = None,
                 app_path:    Optional[str] = None,
                 verbose:     bool = False):
        self.board       = board
        self.binary_path = binary_path
        self.app_path    = os.path.expanduser(app_path) if app_path else None
        self.verbose     = verbose

        flash_cfg        = board["flash"]
        self._openocd    = self._expand(flash_cfg["openocd"])
        self._scripts    = [self._expand(s) for s in flash_cfg["scripts"]]
        self._interface  = self._expand(flash_cfg["interface"])
        self._address    = flash_cfg["address"]
        self._binary_key = flash_cfg["binary_key"]

    # ── Public interface ───────────────────────────────────────────────────────

    def flash(self) -> FlashResult:
        """Flash the binary to the MCU. Returns a FlashResult."""
        start  = time.monotonic()
        result = FlashResult()

        try:
            binary = self._resolve_binary()
            if not os.path.exists(binary):
                result.error = f"Binary not found: {binary}"
                return result

            binary_size = os.path.getsize(binary)

            # Write a temporary flash config pointing to our binary
            flash_cfg = self._write_flash_config(binary)
            try:
                self._run_openocd(flash_cfg)
            finally:
                os.unlink(flash_cfg)

            result.success = True
            result.elapsed = time.monotonic() - start

        except Exception as e:
            result.error   = str(e)
            result.elapsed = time.monotonic() - start
            print(f"[flash] ERROR: {e}")

        return result

    # ── Private ────────────────────────────────────────────────────────────────

    def _resolve_binary(self) -> str:
        """Resolve the binary path. Raises if not determinable."""
        if self.binary_path:
            return os.path.expanduser(self.binary_path)

        if self.app_path:
            candidate = os.path.join(
                self.app_path, ".cache", "sketch", self._binary_key
            )
            if os.path.exists(candidate):
                return candidate

        raise RuntimeError(
            "No binary path provided and could not locate "
            f"{self._binary_key} in app cache."
        )

    def _write_flash_config(self, binary: str) -> str:
        """
        Write a temporary OpenOCD flash config that points to our binary.
        Returns the path to the temp file.
        """
        config = (
            "# HybX flash config — generated by flasher-v2.0.0.py\n"
            "# Always writes to flash, never RAM.\n"
            "reset_config srst_only srst_nogate srst_push_pull connect_assert_srst\n"
            "init\n"
            "reset\n"
            "halt\n"
            "flash info 0\n"
            f"flash write_image erase {{{binary}}} {self._address} bin\n"
            "reset\n"
            "shutdown\n"
        )

        fd, path = tempfile.mkstemp(suffix=".cfg", prefix="hybx_flash_")
        with os.fdopen(fd, "w") as f:
            f.write(config)
        return path

    def _run_openocd(self, flash_cfg: str) -> None:
        """
        Invoke OpenOCD with the flash config.
        Raises RuntimeError on failure.
        """
        cmd = [self._openocd]

        for script_dir in self._scripts:
            cmd += ["-s", script_dir]

        cmd += ["-f", self._interface]
        cmd += ["-f", flash_cfg]

        if self.verbose:
            print("  $ " + " ".join(cmd))

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True
        )

        output = result.stdout + result.stderr

        if self.verbose:
            print(output)

        # OpenOCD exits 0 on success. Any non-zero is a failure.
        if result.returncode != 0:
            # Extract the most useful error line from OpenOCD output
            error_lines = [
                l for l in output.splitlines()
                if any(k in l.lower() for k in ["error", "failed", "fault"])
            ]
            error_summary = error_lines[-1] if error_lines else output[-300:]
            raise RuntimeError(
                f"OpenOCD failed (exit {result.returncode}): {error_summary}"
            )

        # Verify flash write succeeded by checking output
        if "shutdown command invoked" not in output:
            raise RuntimeError(
                "OpenOCD did not complete normally. "
                "Check SWD connection and board power."
            )

    def _expand(self, path: str) -> str:
        """Expand ~ in a path string."""
        return os.path.expanduser(path) if path else path
